<!DOCTYPE HTML>
<HTML LANG=EN>
<HEAD>
    <META CHARSET="UTF-8">
    <TITLE>FIDDLING 1</TITLE>
    <STYLE TYPE="TEXT/CSS">
    LABEL{
        FONT-WEIGHT: BOLD;
        COLOR: #300ACC;
        }
    </STYLE>
</HEAD>
<BODY>
    <!-- THIS IS A COMMENT AS FAR AS I KNOW -->
    <P>THIS PART IS WRITTEN IN HTML, BUT THE BELOW PORTIONS ARE IN PHP</P>

<?PHP
// THIS IS ALSO A COMMENT
# THIS IS A COMMENT TOO
$FILE = $_SERVER['SCRIPT_FILENAME'];
$USER = $_SERVER['HTTP_USER_AGENT'];
$SERVER = $_SERVER['SERVER_SOFTWARE'];
ECHO "HELLO INTERNET, <EM>WELCOME</EM> TO <STRONG>PAPERWOLF!</STRONG>";
ECHO "<BR>FILE = $FILE <BR>USER = $USER <BR>AND SERVER = $SERVER";
?>

<FORM ACTION="HANDLE_FORM2.PHP" METHOD="POST">
    
    <FIELDSET><LEGEND>ENTER YOUR INFORMATION IN THE FORM BELOW:</LEGEND>
    
    <P><LABEL>NAME: <INPUT TYPE="TEXT" NAME="NAME" SIZE="20" MAXLENGTH="40"></LABEL></P>
    
    <P><LABEL>EMAIL ADDRESS: <INPUT TYPE="EMAIL" NAME="EMAIL" SIZE="40" MAXLENGTH="60">
    </LABEL></P>
    
    <P><LABEL FOR="GENDER">GENDER: </LABEL>
    	<INPUT TYPE="RADIO" NAME="GENDER" VALUE="M"> MALE
    	<INPUT TYPE="RADIO" NAME="GENDER" VALUE="F"> FEMALE</P>
    
    <P><LABEL>AGE:
    <SELECT NAME="AGE">
    	<OPTION VALUE="0-29">UNDER 30</OPTION>
    	<OPTION VALUE="30-60">BETWEEN 30 AND 60</OPTION>
    	<OPTION VALUE="60+">OVER 60</OPTION>
    </SELECT></LABEL></P>
    
    <P><LABEL>COMMENTS: <TEXTAREA NAME="COMMENTS" ROWS="3" COLS="40"></TEXTAREA></LABEL></P>
    
    </FIELDSET>
	<P ALIGN="CENTER"><INPUT TYPE="SUBMIT" NAME="SUBMIT" VALUE="SUBMIT MY INFORMATION"></P>

</FORM>

</BODY>
<HTML>
<!-- CABBAGE -->
